"""empty message

Revision ID: 3c394c57c3b1
Revises: a0747230abe9
Create Date: 2019-04-11 23:07:22.873091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c394c57c3b1'
down_revision = 'a0747230abe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('vid_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'vid_hash')
    # ### end Alembic commands ###
