"""empty message

Revision ID: 891cb56e88d6
Revises: 098a5e259e1e
Create Date: 2019-03-08 20:03:07.679058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '891cb56e88d6'
down_revision = '098a5e259e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('liked_by', 'comment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('liked_by', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('liked_by', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('liked_by', 'comment_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
