"""empty message

Revision ID: a0747230abe9
Revises: ac10ae66ca55
Create Date: 2019-03-17 03:21:52.278568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0747230abe9'
down_revision = 'ac10ae66ca55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'likes')
    op.drop_column('video', 'dislikes')
    # ### end Alembic commands ###
