"""empty message

Revision ID: dd81a6cbbb2f
Revises: 891cb56e88d6
Create Date: 2019-03-16 19:28:14.688049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd81a6cbbb2f'
down_revision = '891cb56e88d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liked_by', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('liked_by_ibfk_2', 'liked_by', type_='foreignkey')
    op.create_foreign_key(None, 'liked_by', 'user', ['owner_id'], ['id'])
    op.drop_column('liked_by', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liked_by', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'liked_by', type_='foreignkey')
    op.create_foreign_key('liked_by_ibfk_2', 'liked_by', 'user', ['user_id'], ['id'])
    op.drop_column('liked_by', 'owner_id')
    # ### end Alembic commands ###
